// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info
export const publisher = "ntnyq"
export const name = "vscode-eslint-command"
export const version = "0.0.0"
export const displayName = "ESLint Command"
export const description = "VSCode support for eslint-plugin-command"
export const extensionId = `${publisher}.${name}`

/**
 * Type union of all commands
 */
export type CommandKey = never

/**
 * Commands map registed by `ntnyq.vscode-eslint-command`
 */
export const commands = {
} satisfies Record<string, CommandKey>

/**
 * Type union of all configs
 */
export type ConfigKey = 
  | "vscode-eslint-command.enable"

export interface ConfigKeyTypeMap {
  "vscode-eslint-command.enable": boolean,
}

export interface ConfigShorthandMap {
  enable: "vscode-eslint-command.enable",
}

export interface ConfigItem<T extends keyof ConfigKeyTypeMap> {
  key: T,
  default: ConfigKeyTypeMap[T],
}


/**
 * Configs map registed by `ntnyq.vscode-eslint-command`
 */
export const configs = {
  /**
   * Enable extension
   * @key `vscode-eslint-command.enable`
   * @default `true`
   * @type `boolean`
   */
  enable: {
    key: "vscode-eslint-command.enable",
    default: true,
  } as ConfigItem<"vscode-eslint-command.enable">,
}

export interface ScopedConfigKeyTypeMap {
  "enable": boolean,
}

export const scopedConfigs = {
  scope: "vscode-eslint-command",
  defaults: {
    "enable": true,
  } satisfies ScopedConfigKeyTypeMap,
}

